//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDSapp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Orders
    {
        public long ID { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> RefaundAmount { get; set; }
        public string CustomerCity { get; set; }
    }
}
